### ISSUE TITLE
add (experimental) support for general options in Easystack

### ISSUE THREAD

**Issue by deniskristak** [easybuilders/easybuild-framework#3513]
related to: [easystack file pull request](https://github.com/easybuilders/easybuild-framework/pull/3479)

Additional command-line arguments to EasyBuild can be passed at any level (may even be included outside of `software` scope by specifying a keyword that matches the long argument name, e.g.

```
robot: True
software:
  GROMACS:
    parallel: 6
    toolchains:
      foss-2020a:
        versions:
          2020.1:
          2020.3:
            from_pr: 1234
```
Will be equivalent to running
```

eb GROMAS-2020.1-foss-2020a.eb --robot --parallel=6
eb GROMAS-2020.3-foss-2020a.eb --robot --parallel=6 --from-pr=1234
```

The deepest nested value will always take priority, i.e.
```

software:
  GROMACS:
    parallel: 6
    toolchains:
      foss-2020a:
        versions:
          2020.1:
          2020.3:
            parallel: 12
```
will be equivalent to running

```
eb GROMAS-2020.1-foss-2020a.eb --parallel=6
eb GROMAS-2020.3-foss-2020a.eb --parallel=12
```
