### ISSUE TITLE
add ( experimental ) support for wildcards in Easystack

### ISSUE THREAD

**Issue by deniskristak** [easybuilders/easybuild-framework#3516]
related to: [easystack file pull request](https://github.com/easybuilders/easybuild-framework/pull/3479)
Add support for wildcards when specifying software of toolchain version.

Easystack with wildcards:
```
software:
  binutils:
    toolchains:
      GCCcore-4.9.3:
        versions:
          *
```
should find all matching easyconfigs for specified toolchain and software and proceed with them
