### ISSUE TITLE
also support specifying software via easyconfig filename in easystack files

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3623]
Example:

```yaml
easyconfigs:
    EasyBuild-4.3.3
    GROMACS-2020.1-foss-2020a
      foss-2020a:
        versions:
          2020.1:
          2020.3:
      fosscuda-2020a:
        versions: [2020.1]
    R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0
```

equivalent with:

```yaml
software:
  R-bundle-Bioconductor:
    toolchains:
      foss-2020a:
        versions:
          3.11:
            versionsuffix: '-R-4.0.0'
  EasyBuild:
    toolchains:
      SYSTEM:
        versions: [4.3.3]
  GROMACS:
    toolchains:
      foss-2020a:
        versions:
          2020.1:
          2020.3:
      fosscuda-2020a:
        versions: [2020.1]
  OpenFOAM:
    toolchains:
      foss-2020a:
        versions: [8, v2006]
  R:
    toolchains:
      foss-2020a:
        versions: [4.0.0]
```
