### ISSUE TITLE
also support specifying software via easyconfig filename in easystack files

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3624]
Example:

```yaml
easyconfigs:
    EasyBuild-4.3.3
    GROMACS-2020.1-foss-2020a
    GROMACS-2020.3-foss-2020a
    GROMACS-2020.3-fosscuda-2020a
    OpenFOAM-8-foss-2020a
    OpenFOAM-v2006-foss-2020a
    R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0
```

equivalent with:

```yaml
software:
  R-bundle-Bioconductor:
    toolchains:
      foss-2020a:
        versions:
          3.11:
            versionsuffix: '-R-4.0.0'
  EasyBuild:
    toolchains:
      SYSTEM:
        versions: [4.3.3]
  GROMACS:
    toolchains:
      foss-2020a:
        versions: [2020.1, 2020.3]
      fosscuda-2020a:
        versions: [2020.3]
  OpenFOAM:
    toolchains:
      foss-2020a:
        versions: [8, v2006]
```

A mix of both should also work:

```yaml
easyconfigs:
  EasyBuild-4.3.3
  OpenFOAM-8-foss-2020a
  OpenFOAM-v2006-foss-2020a
  R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0
software:
  GROMACS:
    toolchains:
      foss-2020a:
        versions: [2020.1, 2020.3]
      fosscuda-2020a:
        versions: [2020.3]
