### ISSUE TITLE
add support for specifying required EasyBuild version in easystack file

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#4106]
Example:

```yaml
easybuild-version: 4.6.2
easyconfigs:
    ...
```

If current EasyBuild version doesn't match, then exit with an error?
