### ISSUE TITLE
option 'parallel: 1' seems to not work in an easystack file

### ISSUE THREAD

**Issue by trz42** [easybuilders/easybuild-framework#4258]
Needed to work around some issues building `OpenBLAS-0.3.15-GCC-10.3.0.eb` on a system with `make` v4.4 (NESSI/2023.04) and it seemed one way was to limit make to a single process/job using `--parallel 1` which works without using an easystack file. However, setting this in an easystack file, for example,
```yaml
easyconfigs:
  - OpenBLAS-0.3.15-GCC-10.3.0.eb:
      options:
        parallel: 1
```

resulted in messages such as
```
Usage: eb [options] easyconfig [...]

eb: error: --parallel option requires 1 argument
```

Strangely, `parallel: 2` might work (as pointed out by @bedroge).
