### ISSUE TITLE
Can't use multiple `--try-amend` statements in Easystack entry

### ISSUE THREAD

**Issue by cgross95** [easybuilders/easybuild-framework#4643]
We install MATLAB using something like

``` bash
eb MATLAB-2023b.eb \
    --try-amend="license_server=hostname" \
    --try-amend="license_server_port=12345" \
    --try-amend="key=abc-123"
```

But the equivalent Easystack will only use the last value, e.g., 

``` bash
easyconfigs:
- MATLAB-2023b.eb:
    options:
      try-amend: "license_server=hostname"
      try-amend: "license_server_port=12345"
      try-amend: "key=abc-123"
```

gives a tweaked EasyConfig that only has `key=abc123` at the bottom. `license_server` and `license_server_port` are ignored.

**Comment by Crivella** [comment]
I think this is more a YAML dictionary thing than an easybuild one.
When writing a dictionary in YAML with repeated keys, the last one will be the one considered.

Though it seem that setting it as a list does not lead to the expected behavior

**Comment by ocaisa** [comment]
What about trying
```yaml
easyconfigs:
- MATLAB-2023b.eb:
    options:
      try-amend: 
        - "license_server=hostname\nlicense_server_port=12345\nkey=abc-123"
```
as a hack?

We could probably do something specific for `try-amend` when doing the dict to list argument conversion, I suspect there are very few options that we allow to appear multiple times.
